### ISSUE TITLE
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory) --->Centerface-tensorrt

### ISSUE THREAD

**Issue by sxj731533730** [Star-Clouds/CenterFace#107]
如果你循环执行centerface-tensorrt代码，你将发现以下错误~
If you run the tensorrt-centerface's code in a loop, you will encounter the bottom errors~

[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.3.0 but loaded cuBLAS/cuBLAS LT 11.2.1
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: FAILED_ALLOCATION: std::exception
Traceback (most recent call last):
File "/home/ubuntu/CenterFace/prj-tensorrt/demo.py", line 35, in
test_image_tensorrt(frame,centerface)
File "/home/ubuntu/CenterFace/prj-tensorrt/demo.py", line 14, in test_image_tensorrt
dets, lms = centerface(frame, h, w, threshold=0.35)
File "/home/ubuntu/CenterFace/prj-tensorrt/centerface.py", line 21, in call
return self.inference_tensorrt(img, threshold)
File "/home/ubuntu/CenterFace/prj-tensorrt/centerface.py", line 85, in inference_tensorrt
trt_outputs = do_inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream) # numpy data
File "/home/ubuntu/CenterFace/prj-tensorrt/centerface.py", line 60, in do_inference
context.execute_async(batch_size=batch_size, bindings=bindings, stream_handle=stream.handle)
AttributeError: 'NoneType' object has no attribute 'execute_async'

Process finished with exit code 1

**Comment by sxj731533730** [comment]
i rewrite  the code in Centerface.py

`class CenterFace(object):
    def __init__(self, landmarks=True):
        self.landmarks = landmarks
        self.trt_logger = trt.Logger()  # This logger is required to build an engine
        f = open("centerface.trt", "rb")
        runtime = trt.Runtime(self.trt_logger)
        self.net = runtime.deserialize_cuda_engine(f.read())
        self.img_h_new, self.img_w_new, self.scale_h, self.scale_w = 0, 0, 0, 0
        #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        self.engine = self.net
        # Create the context for this engine
        self.context = self.engine.create_execution_context()
          #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by sxj731533730** [comment]
![C2BFB064-912D-4e57-A5F8-D2E66727AC72](https://user-images.githubusercontent.com/26562321/141405362-563df023-12b8-4e9b-b95c-4a0e13c0c186.png)
