### ISSUE TITLE
TensorRT execution failed

### ISSUE THREAD

**Issue by uday60** [Star-Clouds/CenterFace#63]
Cuda 10.1
Ubuntu 18
TensortRT 6

```
[TensorRT] ERROR: INVALID_CONFIG: The engine plan file is generated on an incompatible device, expecting compute 6.1 got compute 7.5, please rebuild.
[TensorRT] ERROR: engine.cpp (1324) - Serialization Error in deserialize: 0 (Core engine deserialization failure)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "demo.py", line 30, in <module>
    test_image_tensorrt()
  File "demo.py", line 13, in test_image_tensorrt
    dets, lms = centerface(frame, h, w, threshold=0.35)
  File "/opt/github/CenterFace/prj-tensorrt/centerface.py", line 21, in __call__
    return self.inference_tensorrt(img, threshold)
  File "/opt/github/CenterFace/prj-tensorrt/centerface.py", line 73, in inference_tensorrt
    context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

**Comment by dexception** [comment]
Looks like this is going to work on Turing architecture only.

**Comment by oyrq** [comment]
hi,
Maybe your computer environment doesn't match the author's, because the serial file depends on CUDA、GPU driver、GPU and so on

**Comment by ywlife** [comment]
Maybe you can try tensorrt7.

**Comment by dexception** [comment]
@ywlife 
Can mention exact cuda, tensortRT versions for compatibilty ?

**Comment by dexception** [comment]
@ywlife 
[TensorRT] ERROR: INVALID_CONFIG: The engine plan file is generated on an incompatible device, expecting compute 6.1 got compute 7.5, please rebuild.

**Comment by XiaoZiYuan** [comment]
please check your GPU compute capablity in [here](https://developer.nvidia.com/cuda-gpus#compute)

**Comment by jiagh2010** [comment]
tensorrt7    [TensorRT] ERROR: ../rtsafe/corereadarchive.cpp  -serialization error in verifyheader 0 (version tag does not match) @dexception

**Comment by dexception** [comment]
trt file be generated from onnx file. I am not sure about the conversion script.

@ywlife 
Can you share the convertion script ?

**Comment by zhangdengp** [comment]
I got the same problem.but i soloved. you should re-generate .onnx file use your  environment.

**Comment by SusuDOS** [comment]
in my titanx,there was same problem.then I changed my onnx input shape and bulid new trt file from change onnx, finally, python demo.py,that was OK!
