### ISSUE TITLE
How to rubuild trt engine file?

### ISSUE THREAD

**Issue by tms2003** [Star-Clouds/CenterFace#78]
I run trt ,and got this error:

~/source/CenterFace/prj-tensorrt# python demo.py
[TensorRT] ERROR: INVALID_CONFIG: The engine plan file is generated on an incompatible device, expecting compute 6.1 got compute 7.5, please rebuild.
[TensorRT] ERROR: engine.cpp (1324) - Serialization Error in deserialize: 0 (Core engine deserialization failure)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    test_image_tensorrt()
  File "demo.py", line 13, in test_image_tensorrt
    dets, lms = centerface(frame, h, w, threshold=0.35)
  File "/root/source/CenterFace/prj-tensorrt/centerface.py", line 21, in __call__

so ,I can't found rebuild code for trt,how can I rebuild it?

**Comment by nsabir2011** [comment]
Use this [tutorial](https://zhuanlan.zhihu.com/p/106774468)
