### ISSUE TITLE
PyCuda initialization of _driver raised unreported exception Problem

### ISSUE THREAD

**Issue by hanksoga** [Star-Clouds/CenterFace#79]
Environment
- Ubuntu 16.04
- Python 3.5
- Cuda 10.2
- Nvidia Driver 415.25
- CUDNN 7.6.5
- PyCuda 2019.1.2

`ImportError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from centerface import CenterFace
  File "/home/ubuntu/Downloads/CenterFace-master/prj-tensorrt/centerface.py", line 4, in <module>
    import pycuda.autoinit
  File "/usr/local/lib/python3.5/dist-packages/pycuda-2019.1.2-py3.5-linux-x86_64.egg/pycuda/autoinit.py", line 2, in <module>
    import pycuda.driver as cuda
  File "/usr/local/lib/python3.5/dist-packages/pycuda-2019.1.2-py3.5-linux-x86_64.egg/pycuda/driver.py", line 62, in <module>
    from pycuda._driver import *  # noqa
SystemError: initialization of _driver raised unreported exception
`

When I execute /prj-tensorrt/demo.py it will show this error message,can anyone help me to slove this problem?THX.

**Comment by ansivakumar** [comment]
Did you figure this out? Facing the same error

**Comment by sxj731533730** [comment]
i have solved this problem ,you need  run the blow command;

sudo su
export PATH=/usr/local/cuda-11.1/bin:/usr/local/cuda/bin:$PATH 　　
pip install pycuda

fininally, you can use the pycuda to run pyj-tensorrtCenterface  in root 

https://blog.csdn.net/sxj731533730/article/details/121152327
